// Create Event Form
export const FORM_CREATE = 'FORM_CREATE'
export const FORM_MODIFY = 'FORM_MODIFY'
export const FORM_CANCEL = 'FORM_CANCEL'
export const FORM_ADD_CONTACT = 'FORM_ADD_CONTACT'
export const FORM_REMOVE_CONTACT = 'FORM_REMOVE_CONTACT'
export const FORM_CHANGE_NAME = 'FORM_CHANGE_NAME'
export const FORM_CHANGE_DESCRIPTION = 'FORM_CHANGE_DESCRIPTION'
export const FORM_CHANGE_LOCATION_NAME = 'FORM_CHANGE_LOCATION_NAME'
export const FORM_CHANGE_LOCATION = 'FORM_CHANGE_LOCATION'
export const FORM_ADD_DATE = 'FORM_ADD_DATE'
export const FORM_REMOVE_DATE = 'FORM_REMOVE_DATE'
export const FORM_CHANGE_LENGTH = 'FORM_CHANGE_LENGTH'
export const FORM_CHANGE_START_TIME = 'FORM_CHANGE_START_TIME'
export const FORM_CHANGE_RSVP_DEADLINE = 'FORM_CHANGE_RSVP_DEADLINE'
export const FORM_CHANGE_MIN_ATENDEES = 'FORM_CHANGE_MIN_ATENDEES'
export const FORM_CHANGE_MAX_ATENDEES = 'FORM_CHANGE_MAX_ATENDEES'

// Contacts
export const CONTACTS_PERMISSION_CHECK = 'CONTACTS_PERMISSION_CHECK'
export const CONTACTS_PERMISSION_REQUEST = 'CONTACTS_PERMISSION_REQUEST'
export const CONTACTS_PERMISSION_AUTHORIZED = 'CONTACTS_PERMISSION_AUTHORIZED'
export const CONTACTS_PERMISSION_DENIED = 'CONTACTS_PERMISSION_DENIED'
export const CONTACTS_LIST_FETCHED = 'CONTACTS_LIST_FETCHED'

// Location
export const LOCATION_PERMISSION_CHECK = 'LOCATION_PERMISSION_CHECK'
export const LOCATION_PERMISSION_REQUEST = 'LOCATION_PERMISSION_REQUEST'
export const LOCATION_PERMISSION_AUTHORIZED = 'LOCATION_PERMISSION_AUTHORIZED'
export const LOCATION_PERMISSION_DENIED = 'LOCATION_PERMISSION_DENIED'
export const LOCATION_CURRENT_USER_FETCHED = 'LOCATION_CURRENT_USER_FETCHED'

// Event
export const USER_EVENTS_REQUEST = 'USER_EVENTS_REQUEST'
export const USER_EVENTS_REQUEST_SUCCESS = 'USER_EVENTS_REQUEST_SUCCESS'
export const USER_EVENT_SELECTED = 'USER_EVENT_SELECTED'
export const USER_EVENT_ATTENDANCES_MODIFIED = 'USER_EVENT_ATTENDANCES_MODIFIED'
export const USER_EVENT_CANCEL = 'USER_EVENT_CANCEL'
export const USER_EVENT_CREATE = 'USER_EVENT_CREATE'
export const USER_EVENT_MODIFY_FIELDS = 'USER_EVENT_MODIFY_FIELDS'

export type Contact = Object

export type Action =
  { type: 'FORM_ADD_CONTACT', contact: Contact }
  | { type: 'FORM_REMOVE_CONTACT', contact: Contact }
  | { type: 'CONTACTS_PERMISSION_REQUEST' }
  | { type: 'CONTACTS_PERMISSION_SUCCESS', contacts: Array<Contact> }
  | { type: 'CONTACTS_PERMISSION_DENIED', error: string }
